# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmina',
            name='id',
        ),
        migrations.RemoveField(
            model_name='okreg',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wojewodztwo',
            name='id',
        ),
        migrations.AlterField(
            model_name='gmina',
            name='numer',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='okreg',
            name='numer',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wojewodztwo',
            name='numer',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='obwod',
            unique_together=set([('numer', 'gmina')]),
        ),
        migrations.AlterUniqueTogether(
            name='wynik',
            unique_together=set([('kandydat', 'obwod')]),
        ),
    ]
