# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0002_auto_20170414_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statystyka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etykieta', models.CharField(max_length=32)),
                ('liczba', models.IntegerField()),
                ('obwod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.Obwod')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='statystyka',
            unique_together=set([('etykieta', 'obwod')]),
        ),
    ]
