# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_auto_20170416_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatystykaOkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etykieta', models.CharField(max_length=32)),
                ('liczba', models.IntegerField()),
                ('okreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.Okreg')),
            ],
        ),
        migrations.CreateModel(
            name='WynikOkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_glosow', models.IntegerField()),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.Kandydat')),
                ('okreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.Okreg')),
            ],
        ),
        migrations.RenameModel(
            old_name='Statystyka',
            new_name='StatystykaObw',
        ),
        migrations.RenameModel(
            old_name='Wynik',
            new_name='WynikObw',
        ),
        migrations.AlterUniqueTogether(
            name='wynikokr',
            unique_together=set([('kandydat', 'okreg')]),
        ),
        migrations.AlterUniqueTogether(
            name='statystykaokr',
            unique_together=set([('etykieta', 'okreg')]),
        ),
    ]
